### ISSUE TITLE
Add transition in navbar anchor tags 

### ISSUE THREAD

**Issue by Ayan-thecodeking** [Coders-Evoke-Community/CodersEvoke_website#102]
Box one in hover effect

**Comment by dilroseR** [comment]
> Box one in hover effect

can i know more about this?

**Comment by Ayan-thecodeking** [comment]
> > Box one in hover effect
> 
> can i know more about this?

hey @dilroseR just search in google how transition hover effect works and try to implement ...u are also free to do any customization if you have any better idea ...would u like to work on this

**Comment by dilroseR** [comment]
i would like to give it a try

**Comment by Ayan-thecodeking** [comment]
> i would like to give it a try

Go ahead @dilroseR
