### ISSUE TITLE
Add backend in contact us page 

### ISSUE THREAD

**Issue by Ayan-thecodeking** [Coders-Evoke-Community/CodersEvoke_website#103]

**Comment by jigar-sable** [comment]
As PHP, AJAX or [PHPMailer](https://github.com/PHPMailer/PHPMailer) will not work on GH Pages. I think it would be better to use JS Library such as [EmailJS](https://www.emailjs.com/) to send mails after form submission. 

Let me know if using EmailJS I'll integrate it, you just have to change few credentials later.

**Comment by Ayan-thecodeking** [comment]
> As PHP, AJAX or [PHPMailer](https://github.com/PHPMailer/PHPMailer) will not work on GH Pages. I think it would be better to use JS Library such as [EmailJS](https://www.emailjs.com/) to send mails after form submission.
> 
> Let me know if using EmailJS I'll integrate it, you just have to change few credentials later.

ya sure @jigar-sable it will be good for now ....would u like to work on this ??

**Comment by jigar-sable** [comment]
@Ayan-thecodeking Yeah, I would like to work on this. Assign me.

**Comment by Ayan-thecodeking** [comment]
> @Ayan-thecodeking Yeah, I would like to work on this. Assign me.

sure @jigar-sable
