### ISSUE TITLE
Add more sections on home page 

### ISSUE THREAD

**Issue by Ayan-thecodeking** [Coders-Evoke-Community/CodersEvoke_website#111]
Implement your ideas in home page to make it attractive

**Comment by inimitable034** [comment]
I have added a floating Social-network element which on hover splits into 3 similar balls containing the link to coders-evoke social handles.
Please assign me this issue.
I will upload it by evening.

**Comment by Ayan-thecodeking** [comment]
ya sure @inimitable034 .....add one ss or clip before making PR and make it responsive

**Comment by inimitable034** [comment]
https://user-images.githubusercontent.com/71227590/126861624-71f8a16c-0a98-4e66-b2e7-885f39e9757a.mp4

**Comment by inimitable034** [comment]
I have corrected the background image fault of the logo too.

**Comment by Ayan-thecodeking** [comment]
> I have corrected the background image fault of the logo too.

U hv added this in navbar ?? @inimitable034

**Comment by inimitable034** [comment]
no sir
its not a nav bar element. 
this is present below the nav bar as a separate section

**Comment by Ayan-thecodeking** [comment]
Ok make a PR

**Comment by inimitable034** [comment]
PR requested sir,
