### ISSUE TITLE
Remove blur effect from contact page navbar

### ISSUE THREAD

**Issue by Ayan-thecodeking** [Coders-Evoke-Community/CodersEvoke_website#112]
Add hover effect same what we have in home page

**Comment by Anupam-Panwar** [comment]
I would like to work on this issue

**Comment by maitridshah** [comment]
I raised it before, opportunities and events also have same issue. Please assign me this under DCP'21

**Comment by Ayan-thecodeking** [comment]
> I would like to work on this issue

ya @Anupam-Panwar go ahead ...update contact page

**Comment by Ayan-thecodeking** [comment]
> I raised it before, opportunities and events also have same issue. Please assign me this under DCP'21

@maitridshah ok ...plz make a another issue for opportunities page iIll assign you
