### ISSUE TITLE
Add effects on events page 

### ISSUE THREAD

**Issue by Ayan-thecodeking** [Coders-Evoke-Community/CodersEvoke_website#114]
like hover effects or transitions effects on hackathon boxes and read more button

**Comment by Anupam-Panwar** [comment]
I would like to work on this issue

**Comment by Ayan-thecodeking** [comment]
> I would like to work on this issue

sure @Anupam-Panwar go ahead ...after updating add SS or a clip

**Comment by Anupam-Panwar** [comment]
@Ayan-thecodeking This issue has already been resolved by @Ritwik880 
Should I improve it or leave this issue

**Comment by Ayan-thecodeking** [comment]
> @Ayan-thecodeking This issue has already been resolved by @Ritwik880
> Should I improve it or leave this issue

ya @Anupam-Panwar improve it ...u your way
