### ISSUE TITLE
the border radius of the header is too much

### ISSUE THREAD

**Issue by ishan-pf** [Coders-Evoke-Community/CodersEvoke_website#115]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Ayan-thecodeking** [comment]
ok @ishan-pf update it ...and add ss before making PR

**Comment by Ritwik880** [comment]
Hey @ishan-pf are u working on this issue??

**Comment by ishan-pf** [comment]
Yes
