### ISSUE TITLE
header logo on home page has issues

### ISSUE THREAD

**Issue by yashsehgal** [Coders-Evoke-Community/CodersEvoke_website#117]
**Describe the bug**
The header logo on the home page has issues, on hovering on it, a rectangular shape is coming on the screen, maybe it's a CSS-related issue. 

![image](https://user-images.githubusercontent.com/62352288/126812485-1519be30-6fd8-4a88-b7ee-4a10e2db20c9.png)
Please look into this :D

**Comment by Ayan-thecodeking** [comment]
ya @yashsehgal  ...would u like to update it

**Comment by inimitable034** [comment]
I have updated the code sir on the sam issue which i solved for the #111 
Now that red background on hover has been removed.
The nav-bar now looks clean.

**Comment by Ayan-thecodeking** [comment]
hey @yashsehgal ...remove that bg on hover from both home and events page

**Comment by Ritwik880** [comment]
Hey @Ayan-thecodeking is this issue solved?
