### ISSUE TITLE
Changes In footer  

### ISSUE THREAD

**Issue by Shubh14Jain** [Coders-Evoke-Community/CodersEvoke_website#119]
![image](https://user-images.githubusercontent.com/33178665/126857589-f2fc45d7-c4e1-4676-ba20-723f2b9fdda4.png)

**Problem Statement**
In the footer section  links part showing  underlines and blue color and in follow us part need to change the design of background effect and Font text.

**Solution :**
As I select red part. I would like to make Both Links part and Follow part Similar With same background effect and Some unique font.

**In Addition **
Changes In Contact us  and Coders Evokes section In font and design.

**Comment by Ayan-thecodeking** [comment]
ya sure @Shubh14Jain go ahead ...update it ASAP

**Comment by Ayan-thecodeking** [comment]
> ya sure @Shubh14Jain go ahead ...update it ASAP
make sure u don't effect the responsiveness
