### ISSUE TITLE
Adding color pellete for everyone to follow color scheme for website

### ISSUE THREAD

**Issue by honeybhardwaj** [Coders-Evoke-Community/CodersEvoke_website#12]
hi i would like to add the color that i used for creating the navbar for the website so that everyone can follow that. those color combination was choosed from adobe color picker

**Comment by rohan-kulkarni-25** [comment]
What happened ? don't think I was this issue was ignored just was thinking about how can we do this !! Please let me know how will you like to do this !!

**Comment by honeybhardwaj** [comment]
@rohan-kulkarni-25   i ll add a png file you could use it. we generally follow a collow pellete png for a site and try to do designing accordingly
