### ISSUE TITLE
Create about us page for Coders Evoke

### ISSUE THREAD

**Issue by Ayan-thecodeking** [Coders-Evoke-Community/CodersEvoke_website#134]
IF u want to work on this issue ....then u have to make a about us page ,just design it related to home page and don't add any details just design a demo page and make a PR  and for more details DM me

**Comment by Ritwik880** [comment]
I am working on this @Ayan-thecodeking

**Comment by Ayan-thecodeking** [comment]
Hey @Ritwik880 make some thing good ...interactive designn
