### ISSUE TITLE
Design about us page for coders Evoke 

### ISSUE THREAD

**Issue by Ayan-thecodeking** [Coders-Evoke-Community/CodersEvoke_website#139]
![Screenshot (23)](https://user-images.githubusercontent.com/78692566/126908611-9b4a0b3e-2c0a-4e0b-bfd1-a92394e39bb8.png)

**Comment by Shubh14Jain** [comment]
I would like to work on this page

**Comment by Ayan-thecodeking** [comment]
ya @Shubh14Jain go ahead

**Comment by Ayan-thecodeking** [comment]
hey @Shubh14Jain let me know u are working or not

**Comment by Shubh14Jain** [comment]
Hello @Ayan-thecodeking I am working on about page

**Comment by Ritwik880** [comment]
Hey @Ayan-thecodeking I think the about page is working, please have a look:

![Uploading Screenshot (337).png…]()

**Comment by aditya687** [comment]
I would like to work on this issue. This can  be completed within a short interval of time. Please assign me this @Ayan-thecodeking
