### ISSUE TITLE
Updating README.md

### ISSUE THREAD

**Issue by honeybhardwaj** [Coders-Evoke-Community/CodersEvoke_website#14]
Hi,
I would like to update the Read me file to add the necessary things.

thanks
Honey

**Comment by Sarthakjain594** [comment]
heyy , 

Can I try to  work on this as well ??

**Comment by Ayan-thecodeking** [comment]
ya sure go for it

**Comment by Ayan-thecodeking** [comment]
> heyy ,
> 
> Can I try to work on this as well ??

sure ..go for it

**Comment by rohan-kulkarni-25** [comment]
Hey, @Ayan-thecodeking  Sorry to cut you here !! But @honeybhardwaj  asked in the comment that he will like to work on this issue !! It's not fair to assign an issue who asks second !! This is Ok for this time we all are learning here but this will create big issues when working on real-world projects! Please keep in mind !! You can go with this @Sarthakjain594  If @honeybhardwaj  has no objection !! 

Please let @Sarthakjain594  know about this @honeybhardwaj  !! 

HAPPY CONTRIBUTIONS !!

**Comment by Sarthakjain594** [comment]
heyy  @honeybhardwaj , 
 Pls let me know your view .

**Comment by honeybhardwaj** [comment]
> Hey, @Ayan-thecodeking Sorry to cut you here !! But @honeybhardwaj asked in the comment that he will like to work on this issue !! It's not fair to assign an issue who asks second !! This is Ok for this time we all are learning here but this will create big issues when working on real-world projects! Please keep in mind !! You can go with this @Sarthakjain594 If @honeybhardwaj has no objection !!
> 
> Please let @Sarthakjain594 know about this @honeybhardwaj !!
> 
> HAPPY CONTRIBUTIONS !!

really i appreciate that @rohan-kulkarni-25 , No issue @Sarthakjain594  you can continue to work on it i dont have any problem

**Comment by Ayan-thecodeking** [comment]
> Hey, @Ayan-thecodeking Sorry to cut you here !! But @honeybhardwaj asked in the comment that he will like to work on this issue !! It's not fair to assign an issue who asks second !! This is Ok for this time we all are learning here but this will create big issues when working on real-world projects! Please keep in mind !! You can go with this @Sarthakjain594 If @honeybhardwaj has no objection !!
> 
> Please let @Sarthakjain594 know about this @honeybhardwaj !!
> 
> HAPPY CONTRIBUTIONS !!

so sry actually I hv assigned someone first time

**Comment by Sarthakjain594** [comment]
@honeybhardwaj @rohan-kulkarni-25 @Ayan-thecodeking Thanks I will try my best

**Comment by Sarthakjain594** [comment]
Pls give me a gist of what content do we need to add in here .

**Comment by honeybhardwaj** [comment]
@Sarthakjain594 whatever that will be useful for the intro page about this repo such as  its description, guidelines, desrciption of directores . contributors at bottom etc

**Comment by rohan-kulkarni-25** [comment]
Fixes #18
