### ISSUE TITLE
adding responiveness to the mobile and tablet version

### ISSUE THREAD

**Issue by ishan-pf** [Coders-Evoke-Community/CodersEvoke_website#146]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Ayan-thecodeking** [comment]
hey @ishan-pf which page u want to add responsiveness let me know

**Comment by ishan-pf** [comment]
Adding responsiveness to the home page for mobile & tablet version

**Comment by Ayan-thecodeking** [comment]
> Adding responsiveness to the home page for mobile & tablet version

ya sure @ishan-pf go ahead ...before making a PR add a clip showing what u have updated ....try to add on other pages too if possible

**Comment by aditya687** [comment]
Can I try this issue @Ayan-thecodeking ?

**Comment by Ayan-thecodeking** [comment]
hey @ishan-pf updates
