### ISSUE TITLE
Code Architechture of Our Website ! 

### ISSUE THREAD

**Issue by rohan-kulkarni-25** [Coders-Evoke-Community/CodersEvoke_website#15]
## We need this in readme !! Please let me know if you will like to add it ! 

If you don't know the layout of our website let me know I will tell you !! 

![image](https://user-images.githubusercontent.com/76584243/121218406-54ebe380-c8a0-11eb-97dd-fab18158c454.png)

**Comment by Sarthakjain594** [comment]
heyy @rohan-kulkarni-25  , 
Can I add this ?

**Comment by rohan-kulkarni-25** [comment]
OK, @Sarthakjain594  !! We have to add the website layout like this !! 

there is one assets folder in which there are two folders in which one is CSS and the other is images so We want that every single image should be added to the image folder and all CSS files should be added in CSS ! 

then we have js folder where all script files will be added !

**Comment by Sarthakjain594** [comment]
okkk so above given image is an example . I need to make it for our website layout .

**Comment by Sarthakjain594** [comment]
Heyy , 
Can I have some help regarding this issue ??

**Comment by Sarthakjain594** [comment]
heyy @rohan-kulkarni-25  , 
should I remove the existing repo structure ,then add thsi tree structure or just add it as well ?

**Comment by rohan-kulkarni-25** [comment]
> 
> 
> heyy @rohan-kulkarni-25 ,
> should I remove the existing repo structure ,then add thsi tree structure or just add it as well ?

Yes remove that one but please send the image here which you will be going to add

**Comment by Sarthakjain594** [comment]
okkk

**Comment by Sarthakjain594** [comment]
![Screenshot 2021-06-09 110856](https://user-images.githubusercontent.com/77162721/121299537-33780f80-c913-11eb-8294-6882b8fc7e80.png)
This one .

**Comment by rohan-kulkarni-25** [comment]
@Sarthakjain594 
 
 add pages folder as js it will be there for sure !!

**Comment by ujju20** [comment]
Can I also work on this?

**Comment by Ayan-thecodeking** [comment]
> Can I also work on this?

hey @ujju20  what u want to add ...?

**Comment by rohan-kulkarni-25** [comment]
any update ?

**Comment by ankitapuri** [comment]
Is this issue resolved ?

**Comment by Sarthakjain594** [comment]
This issue is already resolved @rohan-kulkarni-25 .

**Comment by ankitapuri** [comment]
@rohan-kulkarni-25 if its done , then please close it
