### ISSUE TITLE
Navbar issue

### ISSUE THREAD

**Issue by PrakharSahu02** [Coders-Evoke-Community/CodersEvoke_website#152]
In the navbar, the navigation button does not work. They do not navigate to the right page. 
at the homepage, about us, opportunities other pages are navigated but after going to that page homepage and some also not navigate.
fix that issue so you can navigate any page from home, about, and all others.....

**Comment by PrakharSahu02** [comment]
I can solve this issue

**Comment by Ayan-thecodeking** [comment]
ok @PrakharSahu02 go ahead

**Comment by aditya687** [comment]
I would like to work on this issue @Ayan-thecodeking

**Comment by Ayan-thecodeking** [comment]
> I would like to work on this issue @Ayan-thecodeking

@aditya687 y u are always late ...just create ur own issue  this issue is already assign
