### ISSUE TITLE
Add a Custom Scroll Bar

### ISSUE THREAD

**Issue by mayank-wadhwa-git** [Coders-Evoke-Community/CodersEvoke_website#153]
**Is your feature request related to a problem? Please describe.**
We can add a custom scroll bar in the website which will be of same color as of webpage which can make a good impression.

**Describe the solution you'd like**
I would Like to add the scroll bar

**Comment by Ayan-thecodeking** [comment]
let me know what u want to add ?? clearly

**Comment by mayank-wadhwa-git** [comment]
I want to change the scrollBar highlighted in picture to the scroll bar with the color of background i.e. red or purple.

![CODERS EVOKE and 2 more pages - Personal - Microsoft​ Edge 27-07-2021 23_32_05_LI](https://user-images.githubusercontent.com/68892762/127205097-0af2cdde-c6a7-4dfa-a9b6-ac69ae68b844.jpg)

**Comment by Ayan-thecodeking** [comment]
ok sure @mayank-wadhwa-git go ahead

**Comment by aditya687** [comment]
Please assign me this issue @Ayan-thecodeking . I can give a nice scroll bar for the site for easy navigation through the page.

**Comment by mayank-wadhwa-git** [comment]
Without hover on scroll Bar

![CODERS EVOKE without hover](https://user-images.githubusercontent.com/68892762/127335572-05f556da-ecb8-437f-9625-8827b9ca96ae.png)

With hover on scroll Bar
![CODERS EVOKE with hover](https://user-images.githubusercontent.com/68892762/127335595-f3619977-1cdb-48fd-ad75-11ed6fabee93.png)

Check @Ayan-thecodeking if the color is fine or should I reverse the color.

**Comment by Ayan-thecodeking** [comment]
ok cool @mayank-wadhwa-git make a pr

**Comment by mayank-wadhwa-git** [comment]
done
