### ISSUE TITLE
Improve display feature of pages by adding AOS library features

### ISSUE THREAD

**Issue by sr-sweta** [Coders-Evoke-Community/CodersEvoke_website#165]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

## Description

All the cards in all pages are static or there is not visual effects in that. That can be much improved using [AOS](http://michalsnik.github.io/aos/) library.

**Comment by Dhruv-194** [comment]
I would like to work on this! Can you please assign me this issue

**Comment by Ayan-thecodeking** [comment]
hey @sr-sweta would u like to work on this issue ??

**Comment by sr-sweta** [comment]
@Ayan-thecodeking Yes, I want to take up this issue as it will be my first issue to this repo :)

**Comment by sr-sweta** [comment]
When you are going to assign me this issue @Ayan-thecodeking . According I have to proceed. Please look into this.

**Comment by Ayan-thecodeking** [comment]
sry @sr-sweta actually i thought i hv already assigned ...go ahead

**Comment by sr-sweta** [comment]
> sry @sr-sweta actually i thought i hv already assigned ...go ahead
> before making a pr add ss here

OK Sure

**Comment by sr-sweta** [comment]
## Description

Added aos libraby in script and added to index.html and event.html.

[Home Page](https://user-images.githubusercontent.com/70569920/127745022-02b279c9-faae-4b36-871d-461a1d831d5a.mp4)


[Event Page](https://user-images.githubusercontent.com/70569920/127745103-29dc8d41-5ecb-4d6c-935b-cb60c8a12473.mp4)
