### ISSUE TITLE
background image and search bar

### ISSUE THREAD

**Issue by PrathamSahu** [Coders-Evoke-Community/CodersEvoke_website#166]
The background image is repeated at the right-side and the search bar is also not look good.
![Screenshot (109)](https://user-images.githubusercontent.com/80022922/127611172-5743e794-d8c2-45a8-88d5-fb42e35297ab.png)

**Comment by PrathamSahu** [comment]
Assign it to me I fix this issue

**Comment by Ayan-thecodeking** [comment]
hey @PrathamSahu idea is good but we are looking for simple home page ..if we will change the bg image then we have to customize the whole website and if we talk about search bar .....can u tell whats the use of search bar here ??

**Comment by PrathamSahu** [comment]
I do not change bg image I only change its width and only change css of search which is already in navbar of this home page
![Screenshot (109)](https://user-images.githubusercontent.com/80022922/127730772-f96fe54a-9526-43b9-ba9f-07a548f0c7b4.png)
this home page

**Comment by PrathamSahu** [comment]
the new one may look like this 
![Screenshot (112)](https://user-images.githubusercontent.com/80022922/127730859-cd06b0e8-616c-4196-8791-1b13234c701e.png)

**Comment by aditya687** [comment]
Can I work on this issue @Ayan-thecodeking ?
