### ISSUE TITLE
Badges that would be given on successfully joining coders evoke : like bronze, silver, gold etc

### ISSUE THREAD

**Issue by unnati914** [Coders-Evoke-Community/CodersEvoke_website#169]
probably adding a profile section and in that various section like if one completes certain amount of tenure with the community
bronze : 1 month
silver : 2 months 
gold : 6 months 
probably ? 
thoughts?

**Comment by unnati914** [comment]
badges i can make

**Comment by Ayan-thecodeking** [comment]
> badges i can make

wow !! sounds great @unnati914  would be great if u contribute here :)

**Comment by unnati914** [comment]
cool I will start working :)

**Comment by unnati914** [comment]
@Ayan-thecodeking please look into this

**Comment by unnati914** [comment]
done please look at the PR
