### ISSUE TITLE
Redesign About us Page 

### ISSUE THREAD

**Issue by Ayan-thecodeking** [Coders-Evoke-Community/CodersEvoke_website#178]

**Comment by Dhruv-194** [comment]
Hey @Ayan-thecodeking Can I work on this issue?

**Comment by Ayan-thecodeking** [comment]
> Hey @Ayan-thecodeking Can I work on this issue?

Ya sure @Dhruv-194

**Comment by Ayan-thecodeking** [comment]
> @Ayan-thecodeking then please assign me this issue!

go ahead

**Comment by Ayan-thecodeking** [comment]
any updates @Dhruv-194

**Comment by Dhruv-194** [comment]
@Ayan-thecodeking I will do it by today :)

**Comment by Ayan-thecodeking** [comment]
@Dhruv-194 check design ...is out now
