### ISSUE TITLE
Add responsiveness in every page of coders evoke  

### ISSUE THREAD

**Issue by Ayan-thecodeking** [Coders-Evoke-Community/CodersEvoke_website#182]

**Comment by devanshi-code** [comment]
I am not sure that I will be able to do it, but want to give a try can I work on this issue?

**Comment by Ayan-thecodeking** [comment]
> I am not sure that I will be able to do it, but want to give a try can I work on this issue?

ya sure @devanshi-code go ahead ....let us know if u face issues

**Comment by Ayan-thecodeking** [comment]
any updates @devanshi-code

**Comment by devanshi-code** [comment]
trying @Ayan-thecodeking

**Comment by devanshi-code** [comment]
@Ayan-thecodeking I am not able to do it , I am unassigning it to myself ,will try to contribute in any other thing

**Comment by Ayan-thecodeking** [comment]
> @Ayan-thecodeking I am not able to do it , I am unassigning it to myself ,will try to contribute in any other thing

no issues @devanshi-code ask if u have any doubts
