### ISSUE TITLE
Logo Size Difference on each page 

### ISSUE THREAD

**Issue by SAHU-01** [Coders-Evoke-Community/CodersEvoke_website#191]
**Describe the bug**

The logo size on every header is different,all the pages need a fix for it

**To Reproduce**
1. Go to ' any page'
2. Click on 'Header'
3. Scroll down to ' see it has a different size on each'

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/71656941/129139165-40d6db7d-1c89-408c-ae82-715116d135d6.png)
![image](https://user-images.githubusercontent.com/71656941/129139187-dff04418-7a16-4254-8389-c4c4e10b4a46.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by gunjan-g** [comment]
Can i work on this issue, please assign it to me

**Comment by gunjan-g** [comment]
@Ayan-thecodeking Can i work on this issue, please assign it to me

**Comment by Ayan-thecodeking** [comment]
> @Ayan-thecodeking Can i work on this issue, please assign it to me

ya sure @gunjan-g
