### ISSUE TITLE
About us Page is incomplete

### ISSUE THREAD

**Issue by Subhradeep10** [Coders-Evoke-Community/CodersEvoke_website#197]
![Screenshot from 2021-08-16 18-19-11](https://user-images.githubusercontent.com/70656957/129566323-344827bb-9c07-4778-8234-d9f26336b63b.png)

Can anyone build design/ or give some idea so that we can add!

**Comment by Ayan-thecodeking** [comment]
hey @Subhradeep10 actually we are totally re designing our website ...
