### ISSUE TITLE
Home page About us section

### ISSUE THREAD

**Issue by SurabhiSuresh22** [Coders-Evoke-Community/CodersEvoke_website#198]
**Is your feature request related to a problem? Please describe.**
It's not actually a problem, but a feature that I can add to make it look amazing

**Describe the solution you'd like**
Add carousel(sliding effect) in the about us section on the home page. It would look great with that auto sliding effect

**Describe alternatives you've considered**
The sliding is automatic as well as control.

**Additional context**
![image](https://user-images.githubusercontent.com/63139488/129661522-4b7834fa-7e6e-4e8b-941b-a49363e35cc6.png)

**Comment by Ayan-thecodeking** [comment]
can you explain what feature u wnat to add ?? @SurabhiSuresh22

**Comment by SurabhiSuresh22** [comment]
> can you explain what feature u wnat to add ?? @SurabhiSuresh22

 I would like to add a carousel(sliding effect) using bootstrap in the about us section on the home page using 2 more images and quotes. It would look great with that auto sliding effect. It can be automated as well as controlled, a simple image is shown in the issue. 
Thankyou

**Comment by Ayan-thecodeking** [comment]
![WhatsApp Image 2021-08-15 at 11 13 24 AM](https://user-images.githubusercontent.com/78692566/129785952-cf82c997-e293-4270-8161-a0c3ebb5ef85.jpeg)
@SurabhiSuresh22 this is the new design we have redesigned are you up for designeg this ???

**Comment by Ayan-thecodeking** [comment]
@SurabhiSuresh22 u can check home page as well

**Comment by RiyaGupta89** [comment]
@Ayan-thecodeking I can design this, if the image is being provided to me.

**Comment by Ayan-thecodeking** [comment]
@RiyaGupta89 sure you can work ...let me know you are up or not
comment on #200
