### ISSUE TITLE
Home page redesign

### ISSUE THREAD

**Issue by Ayan-thecodeking** [Coders-Evoke-Community/CodersEvoke_website#199]
![Screenshot (44)](https://user-images.githubusercontent.com/78692566/129786951-3be2dc2d-d571-43e7-a6dc-6c7dccac0b5e.png)

**Comment by AKSHATNEMA** [comment]
@Ayan-thecodeking I and @ghulamyazdani will be working on this issue and will design the homepage according to illustration.

**Comment by Ayan-thecodeking** [comment]
> @Ayan-thecodeking I and @ghulamyazdani will be working on this issue and will design the homepage according to illustration.

ya sure bro go ahead 
@AKSHATNEMA

**Comment by Ayan-thecodeking** [comment]
illustrations are updated @AKSHATNEMA  check in assests

**Comment by Ayan-thecodeking** [comment]
@ghulamyazdani let me know about the updates
