### ISSUE TITLE
Header component can be improvised

### ISSUE THREAD

**Issue by yashsehgal** [Coders-Evoke-Community/CodersEvoke_website#205]
**Describe the bug**
The header component is kind of not consistent on every page. We can improvise the respective CSS for it. Right now, It's looking like this 
![image](https://user-images.githubusercontent.com/62352288/130391846-ad7e9183-548b-4d7d-b436-714735a5b348.png)
We can work more on this

**Things to follow up**
- [ ] Layout of the header component
- [ ] Hovering effect
- [ ] Logo is not looking properly when using in mobile (mobile-view) 

If you want @Ayan-thecodeking, I can fix this issue.

**Comment by Ayan-thecodeking** [comment]
@yashsehgal bro we are redesigning the whole website ...you can check out the designs
