### ISSUE TITLE
Fix typos and grammar in the Readme 

### ISSUE THREAD

**Issue by vedanthv** [Coders-Evoke-Community/CodersEvoke_website#215]
The Readme for the project had typos and grammar errors. This makes it look clumsy and not professional. I have fixed all such minor yet important lines.

**Comment by vedanthv** [comment]
I am working on this issue maintainers. I will raise a PR soon

**Comment by Ayan-thecodeking** [comment]
> I am working on this issue maintainers. I will raise a PR soon

yup thanx @vedanthv
