### ISSUE TITLE
New Logo for Community

### ISSUE THREAD

**Issue by honeybhardwaj** [Coders-Evoke-Community/CodersEvoke_website#25]
Hi,
I think we can have suggestions for new logo and this issue can be made open for all so that we can choose best one for community since the current logo i think there can be improvement

Thanks
Honey Bhardwaj

**Comment by ujju20** [comment]
These are some logos which I found suitable
![Logo1](https://www.google.com/imgres?imgurl=https%3A%2F%2Fi.pinimg.com%2F236x%2Fc2%2Fa9%2Fc9%2Fc2a9c9621175a6f04804d0d192a787b0--neon-logo-sg-logo.jpg&imgrefurl=https%3A%2F%2Fwww.pinterest.com%2Fjbbuchanan%2Fcoding-logo%2F&tbnid=_xDPIp-gcVffxM&vet=12ahUKEwiq5u6BxI3xAhWJSSsKHZCzCQQQMygAegUIARCzAQ..i&docid=7XcEZLTSaSU15M&w=236&h=177&q=cool%20%20logos%20for%20code&ved=2ahUKEwiq5u6BxI3xAhWJSSsKHZCzCQQQMygAegUIARCzAQ)

**Comment by ujju20** [comment]
These are some logos which I found suitable
![image](https://user-images.githubusercontent.com/64632969/121566323-045cbd80-ca3b-11eb-874d-e885fca23074.png)
![image](https://user-images.githubusercontent.com/64632969/121566397-18082400-ca3b-11eb-8c9d-0b98d02eb2a3.png)
![image](https://user-images.githubusercontent.com/64632969/121566424-20605f00-ca3b-11eb-8f0c-2f19a64d23da.png)

**Comment by honeybhardwaj** [comment]
@ujju20  try making them customize for the community. we can't take someone else logo just like that

**Comment by ujju20** [comment]
Ok, I will do that.

**Comment by tegveersingh0** [comment]
![dfadaf7e-b6da-466d-8251-a20528b81c9d](https://user-images.githubusercontent.com/75977256/121648414-1da25000-cab5-11eb-9c78-cbb7d36a83ff.jpg)


logo..

**Comment by honeybhardwaj** [comment]
![C](https://user-images.githubusercontent.com/51120790/121651257-0b75e100-cab8-11eb-9674-fda599fd8f2f.png)
i have made this
