### ISSUE TITLE
add license 

### ISSUE THREAD

**Issue by Ayan-thecodeking** [Coders-Evoke-Community/CodersEvoke_website#26]

**Comment by niteshseram** [comment]
Can I work on this?

**Comment by Ayan-thecodeking** [comment]
> Can I work on this?

ya sure @niteshseram  but first u have to join our community coders evoke

**Comment by Ayan-thecodeking** [comment]
> > Can I work on this?
> 
> ya sure @niteshseram but first u have to join our community coders evoke

https://discord.gg/FZusE7FH4q

**Comment by niteshseram** [comment]
Ya sure @Ayan-thecodeking

**Comment by Ayan-thecodeking** [comment]
> Ya sure @Ayan-thecodeking

Ok @niteshseram u can work now

**Comment by niteshseram** [comment]
@Ayan-thecodeking which license are you guys planning to add to this project

**Comment by Ayan-thecodeking** [comment]
> @Ayan-thecodeking which license are you guys planning to add to this project

@niteshseram mit will be good

**Comment by niteshseram** [comment]
> > @Ayan-thecodeking which license are you guys planning to add to this project
> 
> @niteshseram mit will be good

Okay, I will make a PR soon
