### ISSUE TITLE
Navbar Improvement

### ISSUE THREAD

**Issue by Sarthakjain594** [Coders-Evoke-Community/CodersEvoke_website#28]
heyy , Can I make some improvements in navbar design ?

**Comment by kriyanshishah** [comment]
Can I work on Navbar design?

**Comment by dilroseR** [comment]
assign it to me

**Comment by shivani248** [comment]
can i improve navbar ?

**Comment by Ayan-thecodeking** [comment]
hey @shivani248 @dilroseR @kriyanshishah  this issue is closed for now ..
if u want u can work on designing issue34
