### ISSUE TITLE
Create A PR Template 

### ISSUE THREAD

**Issue by rohan-kulkarni-25** [Coders-Evoke-Community/CodersEvoke_website#33]
# Follow the Given Steps :- 
<ul>
<li>Fork</li>
<li>In folder `.github` create a new file  ` PULL_REQUEST_TEMPLATE.md `</li>
<li>Paste the content from the  given link</li>
<li>Go to the link copy the RAW content and paste in the file</li>
<li>commit changes</li>
<li>Create PR</li>
</ul>

## Content 👇🏻
https://github.com/rohan-kulkarni-25/LGM-SOC/blob/main/.github/PULL_REQUEST_TEMPLATE.md

**Comment by Anupam-Panwar** [comment]
Can i work on this issue

**Comment by Sakalya100** [comment]
Can I work on this issue please

**Comment by rohan-kulkarni-25** [comment]
> 
> 
> Can I work on this issue

Yes go for it  !!

**Comment by rohan-kulkarni-25** [comment]
> 
> 
> Can I work on this issue please

You can try if @Anupam-Panwar  unable to do it

**Comment by rohan-kulkarni-25** [comment]
@Anupam-Panwar  DEADLINE :- 7 PM Today

**Comment by kriyanshishah** [comment]
Can I work on this issue?

**Comment by Sakalya100** [comment]
> 
> 
> > Can I work on this issue please
> 
> You can try if @Anupam-Panwar unable to do it

Yes sure

**Comment by rohan-kulkarni-25** [comment]
> 
> 
> Can I work on this issue?

Please read the discussions
