### ISSUE TITLE
Design a website for coders evoke using figma or in png format 

### ISSUE THREAD

**Issue by Ayan-thecodeking** [Coders-Evoke-Community/CodersEvoke_website#34]

**Comment by Ayan-thecodeking** [comment]
i'll be providing all the details ....

**Comment by suvrashaw** [comment]
Interested

**Comment by Ayan-thecodeking** [comment]
> Interested

go ahead @suvrashaw

**Comment by suvrashaw** [comment]
Can you provide me with more details regarding this? Will be easy if we connect on Whatsapp.

**Comment by suvrashaw** [comment]
One of my friends also wants to contribute in design,.

**Comment by kaustavr19** [comment]
Interested.

**Comment by inimitable034** [comment]
Interested in solving this issue

**Comment by Ayan-thecodeking** [comment]
> Can you provide me with more details regarding this? Will be easy if we connect on Whatsapp.

sure @suvrashaw .....can u be able to work with team ?

**Comment by Ayan-thecodeking** [comment]
> > Can you provide me with more details regarding this? Will be easy if we connect on Whatsapp.
> 
> sure @suvrashaw .....can u be able to work with team ?

for details join our discord  https://discord.gg/XMuEPgCj6y
and dm for details

**Comment by Ayan-thecodeking** [comment]
@kaustavr19  @inimitable034  do u want to work in team ?

**Comment by inimitable034** [comment]
> @kaustavr19 @inimitable034 do u want to work in team ?

I would like to work as a team

**Comment by Ayan-thecodeking** [comment]
> > @kaustavr19 @inimitable034 do u want to work in team ?
> 
> I would like to work as a team

ok sure @inimitable034  dm me for details

**Comment by kaustavr19** [comment]
> @kaustavr19 @inimitable034 do u want to work in team ?

I would like to do so.

**Comment by Ayan-thecodeking** [comment]
> > @kaustavr19 @inimitable034 do u want to work in team ?
> 
> I would like to do so.

@inimitable034 @kaustavr19  please join and dm me  https://discord.gg/XMuEPgCj6y

**Comment by Ayan-thecodeking** [comment]
hey @inimitable034  @suvrashaw  whats the status ??

**Comment by inimitable034** [comment]
> hey @inimitable034 @suvrashaw whats the status ??
Implemented new design .
trying to cover the prototype so that understanding the context is easy.

**Comment by Ayan-thecodeking** [comment]
> > hey @inimitable034 @suvrashaw whats the status ??
> > Implemented new design .
> > trying to cover the prototype so that understanding the context is easy.

ok @inimitable034 please update it soon
