### ISSUE TITLE
Edit About Info 

### ISSUE THREAD

**Issue by rohan-kulkarni-25** [Coders-Evoke-Community/CodersEvoke_website#36]
Add Proper information about Community and add  deployment link in that section add a few hashtags related to tech stack and also community 

@Ayan-thecodeking  @Sanika2103  Anyone of you go for it ! 

![image](https://user-images.githubusercontent.com/76584243/123953920-69199100-d9c5-11eb-8628-41f3a4ae8f5c.png)

**Comment by rohan-kulkarni-25** [comment]
@Ayan-thecodeking @Sanika2103  Please have a look

**Comment by Ayan-thecodeking** [comment]
> @Ayan-thecodeking @Sanika2103 Please have a look

sure @rohan-kulkarni-25
