### ISSUE TITLE
Creating mousemove background parallax effect

### ISSUE THREAD

**Issue by aishwaryas15** [Coders-Evoke-Community/CodersEvoke_website#37]

**Comment by Ayan-thecodeking** [comment]
ok @aishwaryas15 go ahead ....and please share the ss of what u have done

**Comment by aishwaryas15** [comment]
> ok @aishwaryas15 go ahead ....and please share the ss of what u have done

It's just a trial one i did for now
![Screenshot (74)](https://user-images.githubusercontent.com/62896706/124578699-12500380-de6c-11eb-9e02-41e17e3defcb.png)
![Screenshot (73)](https://user-images.githubusercontent.com/62896706/124578716-154af400-de6c-11eb-92c6-2c0a49084f82.png)
![Screenshot (72)](https://user-images.githubusercontent.com/62896706/124578740-1c720200-de6c-11eb-8920-a173014d395b.png)

**Comment by Ayan-thecodeking** [comment]
> > ok @aishwaryas15 go ahead ....and please share the ss of what u have done
> 
> It's just a trial one i did for now
> ![Screenshot (74)](https://user-images.githubusercontent.com/62896706/124578699-12500380-de6c-11eb-9e02-41e17e3defcb.png)
> ![Screenshot (73)](https://user-images.githubusercontent.com/62896706/124578716-154af400-de6c-11eb-92c6-2c0a49084f82.png)
> ![Screenshot (72)](https://user-images.githubusercontent.com/62896706/124578740-1c720200-de6c-11eb-8920-a173014d395b.png)

Ok @aishwaryas15...but try to make something unique attractive bg

**Comment by Ayan-thecodeking** [comment]
@aishwaryas15  done or not ?

**Comment by Ritika-Agrawal811** [comment]
Hey. Can I try something for this if it is not done yet?

**Comment by Ayan-thecodeking** [comment]
> Hey. Can I try something for this if it is not done yet?

ya @Ritika-Agrawal811 go ahead ...after completing the task add ss in the PR
