### ISSUE TITLE
Design a logo for Coders Evoke community

### ISSUE THREAD

**Issue by Ayan-thecodeking** [Coders-Evoke-Community/CodersEvoke_website#38]
The Logo should be professional ...
Logo represents coders Evoke community

**Comment by rishabhrathore055** [comment]
pls assign this issue

**Comment by Ayan-thecodeking** [comment]
> pls assign this issue

ya sure @rishabhrathore055

**Comment by lipiseth** [comment]
I would like to work on this

**Comment by Ayan-thecodeking** [comment]
ya sure @lipiseth go ahead

**Comment by lipiseth** [comment]
@Ayan-thecodeking I would like you to review some samples of the logo I created for the assigned issue and let me know how to proceed further, also I have specifically used the color scheme mentioned in the readme.md

1.) ![CodeEvokersLogo](https://user-images.githubusercontent.com/70437135/125601606-67a614c5-c084-40d7-a6ac-be86981c2cb0.png)

2.)  https://user-images.githubusercontent.com/70437135/125601764-4e5017c0-3a99-4d73-9d9f-92d0f8ba9dd2.mp4

**Comment by Ayan-thecodeking** [comment]
hey @lipiseth it is too unprofessional and simple ...we are looking for something like catchy and unique logo...if u want u can try

**Comment by lipiseth** [comment]
@Ayan-thecodeking sure , I will try my best
