### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by anubhav201241** [Coders-Evoke-Community/CodersEvoke_website#40]
**Describe the bug**
In your repository when clicking on your coders-evoke site it is not redirecting to your site please solve it :))

**To Reproduce**
Edit the repo and change that link with that link that is working

**Comment by Ayan-thecodeking** [comment]
> **Describe the bug**
> In your repository when clicking on your coders-evoke site it is not redirecting to your site please solve it :))
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> Edit the repo and change that link with that link that is working

thnx @anubhav201241  for suggestion
:)

**Comment by anubhav201241** [comment]
Welcome :)
