### ISSUE TITLE
CONTRIBUTION

### ISSUE THREAD

**Issue by swathi-469** [Coders-Evoke-Community/CodersEvoke_website#44]
I would like to add contribution guidelines for beginners in open source in a form of contribution.md ..please assign this to me

**Comment by Ayan-thecodeking** [comment]
> I would like to add contribution guidelines for beginners in open source in a form of contribution.md ..please assign this to me

ya sure @swathi-469 .....but can mention what all are u going to add

**Comment by swathi-469** [comment]
I would like to add step-by-step instructions along with resources, links, commands, and so on.

**Comment by Ayan-thecodeking** [comment]
> I would like to add step-by-step instructions along with resources, links, commands, and so on.

 All right !!
 sure @swathi-469 do that

**Comment by swathi-469** [comment]
Thanks a lot

**Comment by swathi-469** [comment]
I am part of DevIncept
