### ISSUE TITLE
Adding a Footer

### ISSUE THREAD

**Issue by souravseal99** [Coders-Evoke-Community/CodersEvoke_website#45]
Tried to implement a basic footer section to the site. 

here's the ss:
![image](https://user-images.githubusercontent.com/69809086/125252866-78c69d00-e316-11eb-8a21-434aee4c8c06.png)

**Comment by Ayan-thecodeking** [comment]
hey @souravseal99 try to make it more attaractive

**Comment by souravseal99** [comment]
Sure @Ayan-thecodeking, do you want to suggest something? Like some more content to put or some assets or maybe any UI references.

**Comment by ayushsoni1010** [comment]
Heyy @Ayan-thecodeking👋

I want to work on this issue. Kindly assign me this under DCP'21
I will create an awesome footer.

**Comment by souravseal99** [comment]
Hi @ayushsoni1010 , I'm actually already working on this issue, under DCP'21. Let me please try for a while, and then I'll surely pass it on to you if I got stuck.

**Comment by ayushsoni1010** [comment]
Sure @souravseal99 
Go ahead :)

**Comment by Ayan-thecodeking** [comment]
> Sure @Ayan-thecodeking, do you want to suggest something? Like some more content to put or some assets or maybe any UI references.

ok @souravseal99  just join our discord server and dm me ..i'll provide u more details there

**Comment by souravseal99** [comment]
> > Sure @Ayan-thecodeking, do you want to suggest something? Like some more content to put or some assets or maybe any UI references.
> 
> ok @souravseal99 just join our discord server and dm me ..i'll provide u more details there

💯

**Comment by ayushsoni1010** [comment]
Heyy @souravseal99 👋

Hope you're doing great!!!
Did you made the footer again, let me know if you're working or not
Else @Ayan-thecodeking you can assign me this issue, By the way, I have resolved the issue and made a fantastic footer.
Hope you like it :)
Thanks✨

**Comment by souravseal99** [comment]
That's great !! @ayushsoni1010 . In that case, drop a message in community server's devincept channel in discord.  We can have a discussion with our admin about this.
I was actually looking for a reference as instructed by our admin. 

cc: @Ayan-thecodeking

**Comment by ayushsoni1010** [comment]
I had already that talked to him :)
Alright I m about to make a PR just waiting for your answer that you are  working or not?

**Comment by Ayan-thecodeking** [comment]
> That's great !! @ayushsoni1010 . In that case, drop a message in community server's devincept channel in discord. We can have a discussion with our admin about this.
> I was actually looking for a reference as instructed by our admin.
> 
> cc: @Ayan-thecodeking

@souravseal99 let me know what are the issues u have ??

**Comment by souravseal99** [comment]
> > That's great !! @ayushsoni1010 . In that case, drop a message in community server's devincept channel in discord. We can have a discussion with our admin about this.
> > I was actually looking for a reference as instructed by our admin.
> > cc: @Ayan-thecodeking
> 
> @souravseal99 let me know what are the issues u have ??

The UI references, that I had searched was not going well with the color scheme of the site, plus I was wondering, if you have something specific in mind, about the contents of the footer. 
please let me know, if you liked the design proposed by @ayushsoni1010 .

**Comment by souravseal99** [comment]
> I had already talked to him :)
> Alright, I m about to make a PR just waiting for your answer that you are working or not?

No problem, if you have already  figured it out, then you can make the PR,  after @Ayan-thecodeking assigns you the issue.
