### ISSUE TITLE
Contact page 

### ISSUE THREAD

**Issue by PranavKapoor28** [Coders-Evoke-Community/CodersEvoke_website#46]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Ayan-thecodeking** [comment]
hey @PranavKapoor28 do u want to work on this issue ??

**Comment by PranavKapoor28** [comment]
Yes I can create a contact page.

**Comment by Ayan-thecodeking** [comment]
> Yes I can create a contact page.

ok @PranavKapoor28 go ahead

**Comment by ayushsoni1010** [comment]
Heyy @Ayan-thecodeking 👋

As I have seen it's been 3days till now, no response and updates from @PranavKapoor28 
So I would like to work on this issue, Kindly assign me this issue under DCP'21.

Let me know @PranavKapoor28 if you're working or not, if you're working on it, that's alright :)
else @Ayan-thecodeking you can assign me 

Thanks✨

**Comment by PranavKapoor28** [comment]
@ayushsoni1010
I am working on it, I was not well for the past 2 days due to vaccine so couldn't work on it. But I will complete it.

You can ask @Ayan-thecodeking to give you some other issue.

**Comment by ayushsoni1010** [comment]
> @ayushsoni1010
> I am working on it, I was not well for the past 2 days due to vaccine so couldn't work on it. But I will complete it.
> 
> You can ask @Ayan-thecodeking to give you some other issue.

Oh okay!
Get well soon @PranavKapoor28 

Sure, Go ahead!

**Comment by PranavKapoor28** [comment]
@Ayan-thecodeking I have made the changes but i cannot add in this repo , as it is showing no that there is no change .

What should i do?

**Comment by Ayan-thecodeking** [comment]
> @Ayan-thecodeking I have made the changes but i cannot add in this repo , as it is showing no that there is no change .
> 
> What should i do?

hey @PranavKapoor28  Im not getting what issue u are facing ...dm me lets have a meet on our discord server ..if ur issue is not resolved yet
