### ISSUE TITLE
Navbar Hover effect 

### ISSUE THREAD

**Issue by rohan-kulkarni-25** [Coders-Evoke-Community/CodersEvoke_website#50]
**Is your feature request related to a problem? Please describe.**

When we hover  over an element in the navbar then something effect should be seen for eg there can be hover effect below that element or the font size can be increased something like that

**Comment by RakeshCharpe** [comment]
I would like to work on this issue under DCP'21 .Please assign to me.

**Comment by neelshah2409** [comment]
Issue is assigned @RakeshCharpe Go forward!!
