### ISSUE TITLE
Adding Favicon as Coder's Evoke Logo 

### ISSUE THREAD

**Issue by rohan-kulkarni-25** [Coders-Evoke-Community/CodersEvoke_website#51]
**Is your feature request related to a problem? Please describe.**

Favicon can be added in website tab it can be coders evoke logo till the design gets  ready

**Comment by RakeshCharpe** [comment]
I would like to work on this under DCP'21 . Assign it to me

**Comment by neelshah2409** [comment]
> I would like to work on this under DCP'21 . Assign it to me

You can go for this issue also but go after one by one issue at a time.

**Comment by lipiseth** [comment]
I would like to work on this issue

**Comment by HarshitPandey251** [comment]
I also want to contribute

**Comment by RakeshCharpe** [comment]
@neelshah2409 Is logo is finalised ? If yes then upload it So as per logo I will add favicon .

**Comment by Ayan-thecodeking** [comment]
> @neelshah2409 Is logo is finalised ? If yes then upload it So as per logo I will add favicon .

hey @RakeshCharpe logo is not updated yet ..I'll let u know soon

**Comment by Ayan-thecodeking** [comment]
> I also want to contribute

hloo @HarshitPandey251 @lipiseth there are more issues where u can contribute have a look there :)

**Comment by RakeshCharpe** [comment]
> > @neelshah2409 Is logo is finalised ? If yes then upload it So as per logo I will add favicon .
> 
> hey @RakeshCharpe logo is not updated yet ..I'll let u know soon 

Sure

**Comment by Ayan-thecodeking** [comment]
hey @RakeshCharpe u can add the logo of coders evoke what we have now ??? can u

**Comment by RakeshCharpe** [comment]
Ok I will...
