### ISSUE TITLE
add contribution.md link to the readme

### ISSUE THREAD

**Issue by Ayan-thecodeking** [Coders-Evoke-Community/CodersEvoke_website#53]
just add it after notice

**Comment by aakankshabhende** [comment]
Can I work on this issue @Ayan-thecodeking

**Comment by Ayan-thecodeking** [comment]
> Can I work on this issue @Ayan-thecodeking as a DCP'21 participant

sure @aakankshabhende go ahead

**Comment by Ayan-thecodeking** [comment]
> > Can I work on this issue @Ayan-thecodeking as a DCP'21 participant
> 
> sure @aakankshabhende go ahead
and just create a different branch while making a PR
