### ISSUE TITLE
Create about us page for Coders Evoke 

### ISSUE THREAD

**Issue by Ayan-thecodeking** [Coders-Evoke-Community/CodersEvoke_website#56]
Kindly mention your creative ideas and views here( what are the details we can add in about us section ) and for more further details regarding coders evoke Dm me ...

**Comment by RakeshCharpe** [comment]
In About Us section we can add our team members and their bio , a short para of organisation ,  some images of organisation or work culture , at last newsletter and updates section and social media handles links. If you like my ideas then I would like to work on this issue under DCP'21.

**Comment by Ayan-thecodeking** [comment]
> In About Us section we can add our team members and their bio , a short para of organisation , some images of organisation or work culture , at last newsletter and updates section and social media handles links. If you like my ideas then I would like to work on this issue under DCP'21.

ok cool @RakeshCharpe go ahead ...well add some illustrations pictures and just give color combinations related to our home page ...for more details join our discord server and dm me

**Comment by RakeshCharpe** [comment]
Ok

**Comment by Ayan-thecodeking** [comment]
any updates @RakeshCharpe

**Comment by RakeshCharpe** [comment]
Yes half work is done ,

**Comment by Ayan-thecodeking** [comment]
> Yes half work is done ,

okh

**Comment by Ayan-thecodeking** [comment]
hey @RakeshCharpe any updates ??

**Comment by Ayan-thecodeking** [comment]
hey @RakeshCharpe let me know ...are u working or not ??

**Comment by aditya687** [comment]
Please assign me the issue @Ayan-thecodeking  to improve the about page.

**Comment by RakeshCharpe** [comment]
> hey @RakeshCharpe let me know ...are u working or not ?
My exams goes on that's why i am unable to work on this issue .

**Comment by RakeshCharpe** [comment]
> hey @RakeshCharpe let me know ...are u working or not ??

My exams goes on that's why I am unable to work on this issue.
