### ISSUE TITLE
Add responsiveness is Home page 

### ISSUE THREAD

**Issue by Ayan-thecodeking** [Coders-Evoke-Community/CodersEvoke_website#57]

**Comment by honeybhardwaj** [comment]
i would like to work on it @Ayan-thecodeking . please assign it to me under dcp21

**Comment by Ayan-thecodeking** [comment]
> i would like to work on it @Ayan-thecodeking . please assign it to me under dcp21

sure @honeybhardwaj go ahead

**Comment by Ayan-thecodeking** [comment]
hey @honeybhardwaj  do let me know about updates ??

**Comment by ayushsoni1010** [comment]
Heyy @Ayan-thecodeking @honeybhardwaj 👋

Honey, I would like to know about the status of your work.
If you're working on it, then go ahead
else Ayan, you can assign me this issue, I would like to work on this issue 

Thanks✨
