### ISSUE TITLE
Improvement in navbar

### ISSUE THREAD

**Issue by honeybhardwaj** [Coders-Evoke-Community/CodersEvoke_website#58]
Current navbar have issues with the color combination , space and also when it gets in mobile view the color clashes with the main image. i would like to work on this.

**Comment by Ayan-thecodeking** [comment]
> Current navbar have issues with the color combination , space and also when it gets in mobile view the color clashes with the main image. i would like to work on this.

ok @honeybhardwaj  update that

**Comment by Ayan-thecodeking** [comment]
hey @honeybhardwaj any updates ??
