### ISSUE TITLE
Creating navigation bar using flexbox for the page

### ISSUE THREAD

**Issue by honeybhardwaj** [Coders-Evoke-Community/CodersEvoke_website#6]
Hi, 
The navbar that is created till now have some issues with it like it has some margins above the navbar. also it is made using floats. i would like to make it better using flexbox. kindly assign me this issue.

Thanks 
Honey Bhardwaj

**Comment by rohan-kulkarni-25** [comment]
Ok @honeybhardwaj  !!

**Comment by honeybhardwaj** [comment]
thanks @rohan-kulkarni-25
