### ISSUE TITLE
Add 404 Page

### ISSUE THREAD

**Issue by ri-tae-ka** [Coders-Evoke-Community/CodersEvoke_website#60]
I would like to add a error 404 page to the website.
Please assign me this issue.

**Comment by Naman-mahi** [comment]
Sir please can you assign me

**Comment by neelshah2409** [comment]
@ri-tae-ka Go ahead !! And it is under DCP'21??

**Comment by ri-tae-ka** [comment]
Yes it is. Thanks for allowing me to work on this issue.
Kindly label it under Devincept.
