### ISSUE TITLE
Two Navbar Overlapping

### ISSUE THREAD

**Issue by AnirudhPanda** [Coders-Evoke-Community/CodersEvoke_website#63]
![issue](https://user-images.githubusercontent.com/66218496/125926734-d1e56821-94e9-41ad-9398-94e4da04409e.PNG)

**Comment by neelshah2409** [comment]
@AnirudhPanda You can see the issue #58 and go for that .

**Comment by Ayan-thecodeking** [comment]
hey @AnirudhPanda plz update it ASAP ...till tomorrow by 12 noon is it possible ?? let me know
