### ISSUE TITLE
Scroll to top button should come at midway or end of page

### ISSUE THREAD

**Issue by AnirudhPanda** [Coders-Evoke-Community/CodersEvoke_website#65]
**Describe the bug**
The Scroll to top button should remain hidden on the main page unless the user scrolls

**Comment by neelshah2409** [comment]
@AnirudhPanda Go ahead !!

**Comment by AnirudhPanda** [comment]
#69

**Comment by Ayan-thecodeking** [comment]
> #69

thanks @AnirudhPanda ...keep contributing :)
