### ISSUE TITLE
Create and design the entire 'Project Section' 

### ISSUE THREAD

**Issue by Dhruv-194** [Coders-Evoke-Community/CodersEvoke_website#71]
**Is your feature request related to a problem? Please describe.**
There is no 'Project Page' on the website as of yet.

**Describe the solution you'd like**
I would like to create and design the 'Project Section' of this website which follows the homepage theme.

**Additional context**
I am thinking of using basic HTML,CSS and JavaScript to create this section. I will be using cards to display all the projects with default placeholder text and images. 

Kindly assign me this issue!

**Comment by Ayan-thecodeking** [comment]
hey @Dhruv-194 would u like to work on this ??

**Comment by Dhruv-194** [comment]
Yes @Ayan-thecodeking I would definitely like to work on this. 
Kindly please assign me this issue!

**Comment by Ayan-thecodeking** [comment]
> Yes @Ayan-thecodeking I would definitely like to work on this.
> Kindly please assign me this issue!

@Dhruv-194 go ahead ....just keep it mind that design the other sections related to the home page what we have and do this ASAP
