### ISSUE TITLE
create events page for coders Evoke 

### ISSUE THREAD

**Issue by Ayan-thecodeking** [Coders-Evoke-Community/CodersEvoke_website#82]
for more details DM in on slack or linkdin

**Comment by Amrutha1101** [comment]
Can I work on this issue under DCP'21??

**Comment by Ayan-thecodeking** [comment]
ya sure @Amrutha1101 go ahead and kindly update it ASAP

**Comment by Amrutha1101** [comment]
> for more details DM in on slack or linkdin

I've pinged in slack.

**Comment by Ayan-thecodeking** [comment]
> > for more details DM in on slack or linkdin
> 
> I've pinged in slack.

yup @Amrutha1101 replied

**Comment by Ayan-thecodeking** [comment]
@Amrutha1101 added more images ...check in assets<newimages
