### ISSUE TITLE
create a opportunities page for coders evoke 

### ISSUE THREAD

**Issue by Ayan-thecodeking** [Coders-Evoke-Community/CodersEvoke_website#83]
Design a page related to our home page and add some illustrations images ,use your creativity and design

**Comment by deek121477** [comment]
I can work on this issue

**Comment by Ayan-thecodeking** [comment]
> I can work on this issue

ya sure @deek121477 ..but plz add the files in their respective positions 
go ahead :)

**Comment by deek121477** [comment]
> > I can work on this issue
> 
> ya sure @deek121477 ..but plz add the files in their respective positions
> go ahead :)

Okay

**Comment by Ayan-thecodeking** [comment]
hey @deek121477 any updates ...let me know if u want details , like what we provide

**Comment by deek121477** [comment]
> hey @deek121477 any updates ...let me know if u want details , like what we provide

Due I have to add navbar that is present in index.html

**Comment by Ayan-thecodeking** [comment]
> > hey @deek121477 any updates ...let me know if u want details , like what we provide
> 
> Due I have to add navbar that is present in index.html.I have started created home. html separately.

Yes @deek121477

**Comment by Ayan-thecodeking** [comment]
hey @deek121477 any updates ?? let me know if u have any queries

**Comment by deek121477** [comment]
> hey @deek121477 any updates ?? let me know if u have any queries
Working on it
When I have to submit this?

**Comment by Ayan-thecodeking** [comment]
> > hey @deek121477 any updates ?? let me know if u have any queries
> > Working on it
> > When I have to submit this?

Do it ASAP @deek121477  ...by tomorrow if possible

**Comment by deek121477** [comment]
> > > hey @deek121477 any updates ?? let me know if u have any queries
> > > Working on it
> > > When I have to submit this?
> 
> Do it ASAP @deek121477 ...by tomorrow if possible

Can I submit it by 22nd ?

**Comment by Ayan-thecodeking** [comment]
> > > > hey @deek121477 any updates ?? let me know if u have any queries
> > > > Working on it
> > > > When I have to submit this?
> > 
> > 
> > Do it ASAP @deek121477 ...by tomorrow if possible
> 
> Can I submit it by 22nd ?

Sure @deek121477 take ur time make it responsive

**Comment by deek121477** [comment]
> > > > > hey @deek121477 any updates ?? let me know if u have any queries
> > > > > Working on it
> > > > > When I have to submit this?
> > > 
> > > 
> > > Do it ASAP @deek121477 ...by tomorrow if possible
> > 
> > 
> > Can I submit it by 22nd ?
> 
> Sure @deek121477 take ur time make it responsive

Yeah sure.Thank you

**Comment by deek121477** [comment]
I have completed half of its work. Half will be done by tomorrow.

**Comment by Ayan-thecodeking** [comment]
> I have completed half of its work. Half will be done by tomorrow.

sure @deek121477

**Comment by deek121477** [comment]
![oppo1](https://user-images.githubusercontent.com/67088622/126787523-1690643d-76a7-4ce9-8961-7b388c0ba0c4.PNG)
![oppo2](https://user-images.githubusercontent.com/67088622/126787530-e6722ab5-62f0-4db4-b6bc-808a3aa0938b.PNG)
![oppo3](https://user-images.githubusercontent.com/67088622/126787532-5dceb719-ee01-4b10-b9dc-4db425f45904.PNG)
![oppo4](https://user-images.githubusercontent.com/67088622/126787533-0edfd1b7-7e4d-4015-b7f0-e32876bb15d8.PNG)

This is how it is looking. Should I add any changes?

**Comment by deek121477** [comment]
> ![oppo1](https://user-images.githubusercontent.com/67088622/126787523-1690643d-76a7-4ce9-8961-7b388c0ba0c4.PNG)
> ![oppo2](https://user-images.githubusercontent.com/67088622/126787530-e6722ab5-62f0-4db4-b6bc-808a3aa0938b.PNG)
> ![oppo3](https://user-images.githubusercontent.com/67088622/126787532-5dceb719-ee01-4b10-b9dc-4db425f45904.PNG)
> ![oppo4](https://user-images.githubusercontent.com/67088622/126787533-0edfd1b7-7e4d-4015-b7f0-e32876bb15d8.PNG)
> 
> This is how it is looking. Should I add any changes?

Opportunities spelling would be changed

**Comment by Ayan-thecodeking** [comment]
hey @deek121477 ...please update the repo that u have forked on ur local and then make  a PR ...Design is good ...just add the logo, other is allright

**Comment by Ayan-thecodeking** [comment]
hey @deek121477 plz make a pr again

**Comment by deek121477** [comment]
Okay

**Comment by Ayan-thecodeking** [comment]
> Okay. Do I have to delete the previous repository? Because CSS, images, and HTML pages are still present in it.
> And also I am not getting an option to open a pull request after fetching it upstream.

its ok @deek121477 no need to do  that...thanks for ur contributions  ...
hope u will contribute agian
