### ISSUE TITLE
Spelling mistake in Navbar

### ISSUE THREAD

**Issue by niteshseram** [Coders-Evoke-Community/CodersEvoke_website#86]
**Describe the bug**
In Navbar, _Opportunities_ nav item is misspelled

**Screenshots**
![issue](https://user-images.githubusercontent.com/51370246/126074318-c96cf7b4-9bc1-4423-ad79-6b510c4a5639.JPG)

**Comment by MukulKolpe** [comment]
@niteshseram , can I solve this issue?

**Comment by Ayan-thecodeking** [comment]
hey @niteshseram go ahead !! update it ASAP
and @MukulKolpe look for other issues
