### ISSUE TITLE
add admin section in readme 

### ISSUE THREAD

**Issue by Ayan-thecodeking** [Coders-Evoke-Community/CodersEvoke_website#89]
Just add it below color Scheme for website
happy contributions :)

**Comment by Dhruv-194** [comment]
I would like to work on this but what exactly do I need to write or add in that section?

**Comment by Ayan-thecodeking** [comment]
> @Ayan-thecodeking I would like to work on this but what exactly do I need to write or add in that section?

@Dhruv-194 you have to add my profile under admins section with my handles

**Comment by Dhruv-194** [comment]
> > @Ayan-thecodeking I would like to work on this but what exactly do I need to write or add in that section?
> 
> @Dhruv-194 you have to add my profile under admins section with my handles

got it! Can you please share with me all your social media handles I will add it

**Comment by Ayan-thecodeking** [comment]
> > > @Ayan-thecodeking I would like to work on this but what exactly do I need to write or add in that section?
> > 
> > 
> > @Dhruv-194 you have to add my profile under admins section with my handles
> 
> got it! Can you please share with me all your social media handles I will add it

@Dhruv-194 u will find all my handles in my github profile ,frm there u can take just add twitter and linkdin
