### ISSUE TITLE
Add coders evoke logo in the navbar section 

### ISSUE THREAD

**Issue by Ayan-thecodeking** [Coders-Evoke-Community/CodersEvoke_website#91]
![coders evoke 3](https://user-images.githubusercontent.com/78692566/126115321-c2c2cb9e-1710-4c17-b832-183eaaeb77ad.jpeg)

and add it in this way
![WhatsApp Image 2021-07-18 at 10 59 38 AM](https://user-images.githubusercontent.com/78692566/126115374-b9398b3d-ba52-4b27-8d1f-4bbdf259bd16.jpeg)

**Comment by SarveshLimaye** [comment]
@Ayan-thecodeking would like to work on this issue. Could you pls assign me the issue. I am contributor from devincept.

**Comment by Ayan-thecodeking** [comment]
> @Ayan-thecodeking would like to work on this issue. Could you pls assign me the issue. I am contributor from devincept.

ya sure @SarveshLimaye go ahead

**Comment by Aditya-619** [comment]
Please assigned me, I pretty interested to fix this issue.
