### ISSUE TITLE
Add footer section and in contact us page

### ISSUE THREAD

**Issue by Ayan-thecodeking** [Coders-Evoke-Community/CodersEvoke_website#93]

**Comment by shindesuyog** [comment]
I would like to work on it, Should be similar to the home page or I can customise it.

**Comment by Ayan-thecodeking** [comment]
> I would like to work on it, Should be similar to the home page or I can customise it.

ya sure @shindesuyog go ahead ...add footer and make it responsive ....and u are free to customize the contact us page 
add some cool stuffs

**Comment by Ayan-thecodeking** [comment]
> > I would like to work on it, Should be similar to the home page or I can customise it.
> 
> ya sure @shindesuyog go ahead ...add footer and make it responsive ....and u are free to customize the contact us page
> add some cool stuffs

and if u want illustrations image then ask me ill send u

**Comment by Ayan-thecodeking** [comment]
@shindesuyog any updates ??

**Comment by Ayan-thecodeking** [comment]
> I am working on it , will make pull request by tomorrow.

ok @shindesuyog

**Comment by aditya687** [comment]
I would like to work upon this issue. Please assign me this to improve footer section and contact us page @Ayan-thecodeking

**Comment by Ayan-thecodeking** [comment]
> I would like to work upon this issue. Please assign me this to improve footer section and contact us page @Ayan-thecodeking

hey @aditya687 just create another issue for improvement is contact page i'll assign u

**Comment by aditya687** [comment]
Ok, I'll try to do contact page
