### ISSUE TITLE
Add over all responsiveness in the website 

### ISSUE THREAD

**Issue by Ayan-thecodeking** [Coders-Evoke-Community/CodersEvoke_website#94]

**Comment by souravseal99** [comment]
I would like to work on this.

**Comment by Ayan-thecodeking** [comment]
> I would like to work on this.

sure @souravseal99 go ahead ....update it ASAP 
and u are free to share ur ideas ,like what we can add more

**Comment by souravseal99** [comment]
> > I would like to work on this.
> 
> sure @souravseal99 go ahead ....update it ASAP
> and u are free to share ur ideas ,like what we can add more

💯 
can I use bootstrap to make this process fast ? @Ayan-thecodeking

**Comment by Ayan-thecodeking** [comment]
> > > I would like to work on this.
> > 
> > 
> > sure @souravseal99 go ahead ....update it ASAP
> > and u are free to share ur ideas ,like what we can add more
> 
> 💯
> can I use bootstrap to make this process fast ? @Ayan-thecodeking

@souravseal99 our priority is css ...if u are ok with css then plzz do it with css only ...take some more time ...or if u are using bootstrap just make sure that  it does not effect our existing code
It's ur call now

**Comment by souravseal99** [comment]
> > > > I would like to work on this.
> > > 
> > > 
> > > sure @souravseal99 go ahead ....update it ASAP
> > > and u are free to share ur ideas ,like what we can add more
> > 
> > 
> > 💯
> > can I use bootstrap to make this process fast ? @Ayan-thecodeking
> 
> @souravseal99 our priority is css ...if u are ok with css then plzz do it with css only ...take some more time ...or if u are using bootstrap just make sure that it does not effect our existing code
> It's ur call now

sure @Ayan-thecodeking , no problem. I'll make use of css then.

**Comment by Ayan-thecodeking** [comment]
hey @souravseal99 any updates ??

**Comment by souravseal99** [comment]
> hey @souravseal99 any updates ??

yes @Ayan-thecodeking , I've almost completed the top section of the site, the footer and body is yet to be done.
