### ISSUE TITLE
TEAM PAGE

### ISSUE THREAD

**Issue by pushpakumari5117** [Coders-Evoke-Community/CodersEvoke_website#95]
**DESCRIPTION :** 
I want to design the TEAM PAGE OF CODERS EVOKE Website.

**FEATURES :**
- Image of each team member with their name and designation.
- Will be displayed in the form of Cards UI
- (optional) message/quote from each team member can be added with their image and name.

**You can also suggest some changes to this idea.**

**Comment by neelshah2409** [comment]
@pushpakumari5117 Go ahead. Just keep on thing in mind to make the theme similar to home page or whole website.

**Comment by Ayan-thecodeking** [comment]
hey @neelshah2409 this issue is already created by me #82 look ,
hey @pushpakumari5117 let her make a PR  after u can update according to you , got it ??

**Comment by pushpakumari5117** [comment]
> hey @neelshah2409 this issue is already created by me #82 look ,
> hey @pushpakumari5117 let her make a PR after u can update according to you , got it ??

@Ayan-thecodeking The issue you mentioned is regarding the Events Page. Is the Team page and Events page the same?

**Comment by Ayan-thecodeking** [comment]
so sorry @pushpakumari5117 go ahead ...and plz design the page related to home page what we have ...
make it responsive

**Comment by Ayan-thecodeking** [comment]
> so sorry @pushpakumari5117 go ahead ...and plz design the page related to home page what we have ...
> make it responsive

@pushpakumari5117 have u started ??

**Comment by pushpakumari5117** [comment]
> > so sorry @pushpakumari5117 go ahead ...and plz design the page related to home page what we have ...
> > make it responsive
> 
> @pushpakumari5117 have u started ??

@Ayan-thecodeking Not yet....today only you gave me permission to work on that...so I haven't started yet.

**Comment by Ayan-thecodeking** [comment]
> > > so sorry @pushpakumari5117 go ahead ...and plz design the page related to home page what we have ...
> > > make it responsive
> > 
> > 
> > @pushpakumari5117 have u started ??
> 
> @Ayan-thecodeking Not yet....today only you gave me permission to work on that...so I haven't started yet.

Yup @pushpakumari5117 no issues ...u can start now

**Comment by Ayan-thecodeking** [comment]
any updates @pushpakumari5117

**Comment by pushpakumari5117** [comment]
> any updates @pushpakumari5117

@Ayan-thecodeking I am working on it.

**Comment by Ayan-thecodeking** [comment]
> > any updates @pushpakumari5117
> 
> @Ayan-thecodeking I am working on it.

let me know @pushpakumari5117 when u are going to make a PR

**Comment by Ritwik880** [comment]
Hey @Ayan-thecodeking should I work on this issue?
