### ISSUE TITLE
Fix Horizontal Scrollbar

### ISSUE THREAD

**Issue by AnirudhPanda** [Coders-Evoke-Community/CodersEvoke_website#96]

**Comment by Ayan-thecodeking** [comment]
@AnirudhPanda can u describe what u want to add ??

**Comment by mayank-wadhwa-git** [comment]
I would like to work on it. Can you assign this to me?

**Comment by Ayan-thecodeking** [comment]
> I would like to work on it. Can you assign this to me?

Sure @mayank-wadhwa-git go ahead ...and add ss before making a PR

**Comment by mayank-wadhwa-git** [comment]
assign it to me. I will add ss before PR

**Comment by Ayan-thecodeking** [comment]
> assign it to me. I will add ss before PR

yup @mayank-wadhwa-git go ahead

**Comment by mayank-wadhwa-git** [comment]
Check it once, Should I PR??

Before fixing
![not fixed](https://user-images.githubusercontent.com/68892762/126749950-1244980b-5fff-44c3-95fa-20005dbd77b3.png)
After fixing
![fixed](https://user-images.githubusercontent.com/68892762/126749961-357b81e6-74c4-4e62-ac47-00c922226e86.png)

**Comment by Ayan-thecodeking** [comment]
Ya sure @maya
