### ISSUE TITLE
Add mentors section in Readme 

### ISSUE THREAD

**Issue by Ayan-thecodeking** [Coders-Evoke-Community/CodersEvoke_website#99]
add it below admin section

**Comment by Dexters-Hub** [comment]
Hey @Ayan-thecodeking If you wouldn't mind I would like to work on this 😄

**Comment by neelshah2409** [comment]
@Dexters-Hub Go ahead !!

**Comment by Dexters-Hub** [comment]
Thanks 😃  @neelshah2409 Just need the details of the mentors (Name, What they focus on teaching, social handles)

**Comment by Ayan-thecodeking** [comment]
> Thanks 😃 @neelshah2409 Just need the details of the mentors (Name, What they focus on teaching, social handles)

hey @Dexters-Hub mentors are @neelshah2409 @abhiisinghh7 u can check their profiles for socials and just add their linkdin profiles

**Comment by Dexters-Hub** [comment]
- [x] Added Mentor's name and LinkedIn Profile


![Screenshot (684)](https://user-images.githubusercontent.com/47777599/126502151-db98b2e1-621d-4937-a88f-014fa730bd1c.png)

Should I make a Pull-Request? @neelshah2409 @Ayan-thecodeking

**Comment by Ayan-thecodeking** [comment]
Hey @Dexters-Hub can u align admin image section in center ...and after make a PR
